#include <bits/stdc++.h>
using namespace std;

#define inf LLONG_MAX
#define MAXN 100008

long long n, k, channel[MAXN], minHum;//Number of channels in the mixer (n), Distance (k), Hum generated by each channel, Minimum hum generated (minHum)

int main(){
	
    minHum=inf;
	 
    cin>>n>>k;
    
    for(long long i = 1; i <= n; i++){
        cin>>channel[i];
    }
    
    
    for(long long beg = 1; beg <= k+1; beg++){
    	
        long long hum = 0, nxt = beg;
        
        while(nxt <= n){
        	
            hum += channel[nxt];
            nxt = nxt+2*k+1;
            
        }
        
        nxt=nxt-2*k-1;
        
        if(nxt+k >= n){
        	
            minHum = min(hum,minHum);
            
        }
    }
    
    cout<<minHum<<endl;
    
    return 0;
}
